- name: create loki system group
  group:
    name: "{{ loki_system_group }}"
    system: true
    state: present

- name: create loki system user
  user:
    name: "{{ loki_system_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ loki_system_group }}"
    createhome: "{{ loki_system_user_create_home }}"

- name: "Download loki files"
  become: false
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-amd64.zip"
    dest: "/tmp/"
  delegate_to: localhost

- name: "Create temporary directory"
  become: false
  file:
    path: /tmp/loki-{{loki_version}}-linux-amd64
    state: directory
  delegate_to: localhost

- name: "Unarchive loki files"
  become: false
  unarchive:
    src: "/tmp/loki-linux-amd64.zip"
    remote_src: yes
    dest: /tmp/loki-{{loki_version}}-linux-amd64
    creates: "/tmp/loki-{{loki_version}}-linux-amd64/loki-linux-amd64"
  delegate_to: localhost
  check_mode: false

- name: propagate loki binary
  copy:
    src: "/tmp/loki-{{loki_version}}-linux-amd64/loki-linux-amd64"
    dest: "/usr/local/bin/loki"
    mode: 0755
    owner: "{{ loki_system_user }}"
    group: "{{ loki_system_group }}"
  notify:
    - restart loki

- name: pre-create loki folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ loki_system_user }}"
    group: "{{ loki_system_group }}"
  when: loki_directories|length>0
  loop: "{{ loki_directories }}"

#- name: deploy loki alerts
#  template:
#    src: "alert.rules.j2"
#    dest: "{{ loki_alerts_directory }}/ansible_managed.rules"
#    owner: "{{ loki_system_user }}"
#    group: "{{ loki_system_group }}"
#    mode: 0640
#    validate: "{{ _prometheus_binary_install_dir }}/promtool check rules %s"
#  when:
#    - loki_alert_rules != []
#  notify:
#    - restart loki

- name: configure loki
  template:
    src: loki.yml.j2
    dest: /etc/loki.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - restart loki

- name: create systemd service unit
  template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart loki

- name: Enable and unmask loki service
  systemd:
    daemon_reload: true
    name: loki
    state: started
    enabled: yes
    masked: no
